# Generated by Django 5.1 on 2024-08-15 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="doctor",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="doctor",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="doctor",
            name="middle_name",
        ),
        migrations.AddField(
            model_name="doctor",
            name="user",
            field=models.OneToOneField(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="doctor_profile",
                to="core.customuser",
            ),
            preserve_default=False,
        ),
    ]
